### ISSUE TITLE
Map is not being displayed

### ISSUE THREAD

**Issue by mrabhiram** [MapCompass/MapCompass#1]
The map does not work always on google chrome. Some even report that it often does not show up in the Firefox too. The geolocation API which we use is not reliable. Need to change to a effective and standard one. 
![mapnotshowing](https://f.cloud.github.com/assets/1394059/627302/3c3f5830-d01a-11e2-9a2b-056b902bc535.png)

This is snapshot. Need to be fixed urgently.

**Comment by Yoric** [comment]
Can you reproduce the issue?
Is there an error message in the developer console?

**Comment by mrabhiram** [comment]
There is no error message as such in developer console. That is the big worry to us. To reproduce the error, you can  join a group with the following details.
Click join button in the main page

1.Enter this as groupid : abhiramB0rmZXTeCQ
2. Enter this as username : abhi

You will be taken to the page where you should see map along with your location spotted(Never mind about the UI, its not organized properly).

But, as i posted above, iam not able to see the image when in chrome (ubuntu). I am able to see the map in chrome (windows) and firefox(ubuntu and windows). Firefox has no problem displaying the map. Once the share location button is clicked, when asked it displays the map. So, any ideas.

**Comment by mrabhiram** [comment]
Closed due to error in getting the geolocation. Handled the error.
